server:
  time: updateversion1233
#整合redis实现session共享 start
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 20000
#    cluster:
#      nodes: 192.168.211.134:7000,192.168.211.134:7001
#      -
#      max-redirects:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 #租期到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 10 #租期更新时间间隔（默认30秒）
#整合redis实现session共享 end